steps:
  # Step 1: Install dependencies
  - name: 'node:20'  # Specify the Node.js version
    entrypoint: 'npm'
    args: ['install']

  - name: 'gcr.io/google-appengine/gcloud'
    args:
    - run
    - deploy
    - service-user
    - --image
    - gcr.io/service-user-441015/service-user
    - --platform
    - managed
    - --region
    - southamerica-east1
