steps:
  # Step 1: Install dependencies
  - name: 'node:20'  # Specify the Node.js version
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Run unit tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']  # Adjust this command based on your test script

  - name: 'gcr.io/google-appengine/gcloud'
    args:
    - run
    - deploy
    - service-user
    - --image
    - gcr.io/$PROJECT_ID/service-user
    - --platform
    - managed
    - --region
    - southamerica-east1
