services:
  user_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    container_name: user-service
    env_file: .env
    # environment:
    #   DATABASE_URL: postgresql://user_db:user_db_password@postgres:5432/user_service?schema=public
    depends_on:
      - user_db_server

  user_db_server:
    image: 'postgres:14.0'
    ports:
      - '5432:5432'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./db-data/user_db_server/:/var/lib/postgressql/data
    container_name: postgres
#     restart: always
# volumes:
#   db-data:
