services:
  user_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    container_name: user-service
    # env_file: .env
    environment:
      DATABASE_URL: postgresql://admin:user-service1234@postgres:5432/user-service?socket=/cloudsql/protean-triode-440018-n4:southamerica-east1:us3r-s3rvice
    depends_on:
      - user_db_server

  user_db_server:
    image: 'postgres:16.0'
    ports:
      - '5432:5432'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: user-service1234
      POSTGRES_DB: user-service
    volumes:
      - ./db-data/user_db_server/:/var/lib/postgressql/data
    container_name: postgres
    restart: always
volumes:
  db-data:
